export const metadata = {
  title: "Registrarse - GDG Huancayo",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-slate-100 h-full">
      <body className="h-full">{children}</body>
    </html>
  );
}
